CREATE TABLE climate(
    uuid UUID NOT NULL,
    site VARCHAR(64) NOT NULL,
    ip_address INET NOT NULL,
    latitude NUMERIC NOT NULL,
    longitude NUMERIC NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    record INTEGER NOT NULL,
    airtemp NUMERIC,
    airtemp_min NUMERIC,
    airtemp_max NUMERIC,
    airtemp_avg NUMERIC,
    rh NUMERIC,
    rh_min NUMERIC,
    rh_max NUMERIC,
    rh_avg NUMERIC,
    dewpt NUMERIC,
    dewpt_min NUMERIC,
    dewpt_max NUMERIC,
    dewpt_avg NUMERIC,
    pressure NUMERIC,
    pressure_min NUMERIC,
    pressure_max NUMERIC,
    pressure_avg NUMERIC,
    ws_s_wvt NUMERIC,
    winddir_d1_wvt NUMERIC,
    winddir_sd1_wvt NUMERIC,
    windgust NUMERIC,
    windspd_tmx TIMESTAMP,
    winddir_smpmax NUMERIC,
    sn500_incomingsw_avg NUMERIC,
    sn500_outgoingsw_avg NUMERIC,
    sn500_incominglw_avg NUMERIC,
    sn500_outgoinglw_avg NUMERIC,
    sn500_netsw_avg NUMERIC,
    sn500_netlw_avg NUMERIC,
    sn500_netradiation_total_avg NUMERIC,
    sn500_incomingsw_min NUMERIC,
    sn500_incomingsw_max NUMERIC,
    sn500_outgoingsw_min NUMERIC,
    sn500_outgoingsw_max NUMERIC,
    sn500_incominglw_min NUMERIC,
    sn500_incominglw_max NUMERIC,
    sn500_outgoinglw_min NUMERIC,
    sn500_outgoinglw_max NUMERIC,
    sn500_netsw_min NUMERIC,
    sn500_netsw_max NUMERIC,
    sn500_netlw_min NUMERIC,
    sn500_netlw_max NUMERIC,
    sn500_netradiation_total_min NUMERIC,
    sn500_netradiation_total_max NUMERIC,
    pluvio_intensity_rt NUMERIC,
    pluvio_accu_rt_nrt NUMERIC,
    pluvio_accu_nrt NUMERIC,
    pluvio_accu_total_nrt NUMERIC,
    pluvio_bucket_rt NUMERIC,
    pluvio_bucket_nrt NUMERIC,
    pluvio_temp_lc NUMERIC,
    pluvio_heat_status NUMERIC,
    pluvio_status NUMERIC,
    precip_tot NUMERIC,
    snowdepth_time NUMERIC,
    snowdepth NUMERIC,
    snowdepth_blocktemp NUMERIC,
    snowdepth_ambienttemp NUMERIC,
    snowdepth_lasertemp NUMERIC,
    snowdepth_signal NUMERIC,
    snowdepth_tilt NUMERIC,
    snowdepth_error INTEGER,
    shm31_measured INTEGER,
    parsival_rain_intensity INTEGER,
    parsival_rain_accum INTEGER,
    parsival_wx_code1 INTEGER,
    parsival_visibility INTEGER,
    parsival_sample_int INTEGER,
    parsival_signal_amp INTEGER,
    parsival_particles INTEGER,
    parsival_kin_energy INTEGER,
    parsival_snowdepth_intensity INTEGER,
    parsival_wx_code2 INTEGER,
    parsival_temp_pcb INTEGER,
    parsival_temp_rightsensor INTEGER,
    parsival_temp_leftsensor INTEGER,
    parsival_parsival_status INTEGER,
    parsival_heater_current NUMERIC,
    parsival_power_supply NUMERIC,
    battv NUMERIC NOT NULL
);

ALTER TABLE climate ADD CONSTRAINT climate_constraint UNIQUE (timestamp, site, record);
CREATE INDEX ON climate (site, timestamp DESC);

CREATE TABLE stream_gauge(
    uuid UUID NOT NULL,
    site VARCHAR(64) NOT NULL,
    ip_address INET NOT NULL,
    latitude NUMERIC NOT NULL,
    longitude NUMERIC NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    record INTEGER NOT NULL,
    correctedwl NUMERIC,
    wtemp NUMERIC,
    batt NUMERIC NOT NULL,
    soilm_1 NUMERIC,
    soilm_2 NUMERIC,
    dr1_1 NUMERIC,
    dr1_2 NUMERIC,
    exo_cond NUMERIC,
    exo_level NUMERIC,
    exo_nlfcond NUMERIC,
    exo_odosat NUMERIC,
    exo_odoloc NUMERIC,
    exo_odomgl NUMERIC,
    exo_orpmv NUMERIC,
    exo_psi NUMERIC,
    exo_salpsu NUMERIC,
    exo_spcond NUMERIC,
    exo_tds NUMERIC,
    exo_turbidity NUMERIC,
    exo_tss NUMERIC,
    exo_wiperv NUMERIC,
    exo_ph NUMERIC,
    exo_phmv NUMERIC,
    exo_tempc NUMERIC,
    exo_verticaL NUMERIC
);

ALTER TABLE stream_gauge ADD CONSTRAINT stream_gauge_constraint UNIQUE (timestamp, site, record);
CREATE INDEX ON stream_gauge (timestamp DESC);

CREATE TABLE lake_level(
    uuid UUID NOT NULL,
    site VARCHAR(64) NOT NULL,
    ip_address INET NOT NULL,
    latitude NUMERIC NOT NULL,
    longitude NUMERIC NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    record INTEGER NOT NULL,
    stage NUMERIC NOT NULL,
    battv NUMERIC NOT NULL
);

ALTER TABLE lake_level ADD CONSTRAINT lake_level_constraint UNIQUE (timestamp, site, record);
CREATE INDEX ON lake_level (timestamp DESC);

CREATE TABLE lake_profile(
    uuid UUID NOT NULL,
    site VARCHAR(64) NOT NULL,
    ip_address INET NOT NULL,
    latitude NUMERIC NOT NULL,
    longitude NUMERIC NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    record INTEGER NOT NULL,
    pfl_counter INTEGER NOT NULL,
    _cntrs232 INTEGER NOT NULL,
    _rs232dpt NUMERIC NOT NULL,
    temp_c NUMERIC,
    odo_mgl NUMERIC,
    odo_prcnt_sat NUMERIC,
    odo_prcnt_local NUMERIC,
    cond_mscm NUMERIC,
    cond_uscm NUMERIC,
    sp_cond_mscm NUMERIC,
    sp_cond_uscm NUMERIC,
    ph NUMERIC,
    tds_gl NUMERIC,
    sal_psu NUMERIC,
    turb_fnu NUMERIC,
    orp_mv NUMERIC,
    chl_ugl NUMERIC,
    phycocyanin_ugl NUMERIC,
    phycocyanin_cellsml NUMERIC,
    phycocyanin_rfu NUMERIC,
    vert_pos_m NUMERIC
);

ALTER TABLE lake_profile ADD CONSTRAINT lake_profile_constraint UNIQUE (timestamp, site, record);
CREATE INDEX ON lake_profile (timestamp DESC);

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
